### PR TITLE
Google Search Engine using Serper API

### PR DESCRIPTION
**Pull request by GithuBarry**
#### 📝 信息 | Information
Saw this [comment](https://github.com/lobehub/lobe-chat/issues/914#issuecomment-1876304049) and hence worked on an simple for [Serper API](https://serper.dev/), which appearantly is free for up to generously 2500 queries a month currently.

#### ✅ 检查列表 | Checklist:

- [x] 我已阅读了 [`Readme.md`](https://github.com/lobehub/lobe-chat-plugins/)
- [x] 描述是用英文编写的。
- [x] `meta.json` 和 `plugin-template.json` 没有被修改过。
- [x] `entry` 放置在 `src` 目录中，并且使用 `.json` 文件扩展名。

---

- [x] I have read the [`Readme.md`](https://github.com/lobehub/lobe-chat-plugins/)
- [x] The description is written in English.
- [x] The `meta.json` and `plugin-template.json` have not been modified.
- [x] The `entry` is placed in the `src` directory with the `.json` file extension.

### CODE REVIEW

**Comment by GithuBarry** [comment]
https://raw.githubusercontent.com/GithuBarry/lobe-chat-plugins/main/src/search-engine-serper.json 
Seems to be valid manifesto file for my deployment despite failed vercel. Free API key required for testing

**Comment by GithuBarry** [comment]
@arvinxx 请求review✌️

**Comment by arvinxx** [comment]
抱歉miss了，我今天看下

**Comment by GithuBarry** [comment]
拍一拍 @arvinxx

**Pull request merged**
